package com.webank.webase.node.mgr.contract.warehouse.mapper;

import com.webank.webase.node.mgr.contract.warehouse.entity.TbContractItem;
import org.apache.ibatis.jdbc.SQL;

public class TbContractItemSqlProvider {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_contract_item
     *
     * @mbg.generated
     */
    public static final String ALL_COLUMN_FIELDS = "id,contract_name,create_time,modify_time,ware_house_id,contract_folder_id,contract_source,description,description_en";

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_contract_item
     *
     * @mbg.generated
     */
    public String insertSelective(TbContractItem record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("tb_contract_item");
        
        if (record.getContractName() != null) {
            sql.VALUES("contract_name", "#{contractName,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getModifyTime() != null) {
            sql.VALUES("modify_time", "#{modifyTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getWareHouseId() != null) {
            sql.VALUES("ware_house_id", "#{wareHouseId,jdbcType=INTEGER}");
        }
        
        if (record.getContractFolderId() != null) {
            sql.VALUES("contract_folder_id", "#{contractFolderId,jdbcType=INTEGER}");
        }
        
        if (record.getContractSource() != null) {
            sql.VALUES("contract_source", "#{contractSource,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getDescription() != null) {
            sql.VALUES("description", "#{description,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getDescriptionEn() != null) {
            sql.VALUES("description_en", "#{descriptionEn,jdbcType=LONGVARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_contract_item
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(TbContractItem record) {
        SQL sql = new SQL();
        sql.UPDATE("tb_contract_item");
        
        if (record.getContractName() != null) {
            sql.SET("contract_name = #{contractName,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getModifyTime() != null) {
            sql.SET("modify_time = #{modifyTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getWareHouseId() != null) {
            sql.SET("ware_house_id = #{wareHouseId,jdbcType=INTEGER}");
        }
        
        if (record.getContractFolderId() != null) {
            sql.SET("contract_folder_id = #{contractFolderId,jdbcType=INTEGER}");
        }
        
        if (record.getContractSource() != null) {
            sql.SET("contract_source = #{contractSource,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getDescription() != null) {
            sql.SET("description = #{description,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getDescriptionEn() != null) {
            sql.SET("description_en = #{descriptionEn,jdbcType=LONGVARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}