package com.webank.webase.node.mgr.contract.warehouse.mapper;

import com.webank.webase.node.mgr.contract.warehouse.entity.TbWareHouse;
import org.apache.ibatis.jdbc.SQL;

public class TbWareHouseSqlProvider {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_ware_house
     *
     * @mbg.generated
     */
    public static final String ALL_COLUMN_FIELDS = "id,ware_house_name,ware_house_name_en,type,create_time,modify_time,ware_house_icon,description,description_en,ware_house_detail,ware_house_detail_en";

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ware_house
     *
     * @mbg.generated
     */
    public String insertSelective(TbWareHouse record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("tb_ware_house");
        
        if (record.getWareHouseName() != null) {
            sql.VALUES("ware_house_name", "#{wareHouseName,jdbcType=VARCHAR}");
        }
        
        if (record.getWareHouseNameEn() != null) {
            sql.VALUES("ware_house_name_en", "#{wareHouseNameEn,jdbcType=VARCHAR}");
        }
        
        if (record.getType() != null) {
            sql.VALUES("type", "#{type,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getModifyTime() != null) {
            sql.VALUES("modify_time", "#{modifyTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getWareHouseIcon() != null) {
            sql.VALUES("ware_house_icon", "#{wareHouseIcon,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getDescription() != null) {
            sql.VALUES("description", "#{description,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getDescriptionEn() != null) {
            sql.VALUES("description_en", "#{descriptionEn,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getWareHouseDetail() != null) {
            sql.VALUES("ware_house_detail", "#{wareHouseDetail,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getWareHouseDetailEn() != null) {
            sql.VALUES("ware_house_detail_en", "#{wareHouseDetailEn,jdbcType=LONGVARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ware_house
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(TbWareHouse record) {
        SQL sql = new SQL();
        sql.UPDATE("tb_ware_house");
        
        if (record.getWareHouseName() != null) {
            sql.SET("ware_house_name = #{wareHouseName,jdbcType=VARCHAR}");
        }
        
        if (record.getWareHouseNameEn() != null) {
            sql.SET("ware_house_name_en = #{wareHouseNameEn,jdbcType=VARCHAR}");
        }
        
        if (record.getType() != null) {
            sql.SET("type = #{type,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getModifyTime() != null) {
            sql.SET("modify_time = #{modifyTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getWareHouseIcon() != null) {
            sql.SET("ware_house_icon = #{wareHouseIcon,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getDescription() != null) {
            sql.SET("description = #{description,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getDescriptionEn() != null) {
            sql.SET("description_en = #{descriptionEn,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getWareHouseDetail() != null) {
            sql.SET("ware_house_detail = #{wareHouseDetail,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getWareHouseDetailEn() != null) {
            sql.SET("ware_house_detail_en = #{wareHouseDetailEn,jdbcType=LONGVARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}