package com.webank.webase.node.mgr.contract.warehouse.mapper;

import com.webank.webase.node.mgr.contract.warehouse.entity.TbWareHouse;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

/**
 * @author marsli
 */
public interface TbWareHouseMapper {

    @Select({"select", TbWareHouseSqlProvider.ALL_COLUMN_FIELDS, "from tb_ware_house"})
    List<TbWareHouse> findAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ware_house
     *
     * @mbg.generated
     */
    @Delete({
        "delete from tb_ware_house",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ware_house
     *
     * @mbg.generated
     */
    @InsertProvider(type=TbWareHouseSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(TbWareHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ware_house
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, ware_house_name, ware_house_name_en, type, create_time, modify_time, ware_house_icon, ",
        "description, description_en, ware_house_detail, ware_house_detail_en",
        "from tb_ware_house",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ware_house_name", property="wareHouseName", jdbcType=JdbcType.VARCHAR),
        @Result(column="ware_house_name_en", property="wareHouseNameEn", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="modify_time", property="modifyTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="ware_house_icon", property="wareHouseIcon", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="description_en", property="descriptionEn", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="ware_house_detail", property="wareHouseDetail", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="ware_house_detail_en", property="wareHouseDetailEn", jdbcType=JdbcType.LONGVARCHAR)
    })
    TbWareHouse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ware_house
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TbWareHouseSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TbWareHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ware_house
     *
     * @mbg.generated
     */
    @Options(useGeneratedKeys = true,keyProperty="id",keyColumn = "id")
    @Insert({
    "<script>",
        "insert into tb_ware_house (ware_house_name, ",
        "ware_house_name_en, type, ",
        "create_time, modify_time, ",
        "ware_house_icon, description, ",
        "description_en, ware_house_detail, ",
        "ware_house_detail_en)",
        "values<foreach collection=\"list\" item=\"detail\" index=\"index\" separator=\",\">(#{detail.wareHouseName,jdbcType=VARCHAR}, ",
        "#{detail.wareHouseNameEn,jdbcType=VARCHAR}, #{detail.type,jdbcType=VARCHAR}, ",
        "#{detail.createTime,jdbcType=TIMESTAMP}, #{detail.modifyTime,jdbcType=TIMESTAMP}, ",
        "#{detail.wareHouseIcon,jdbcType=LONGVARCHAR}, #{detail.description,jdbcType=LONGVARCHAR}, ",
        "#{detail.descriptionEn,jdbcType=LONGVARCHAR}, #{detail.wareHouseDetail,jdbcType=LONGVARCHAR}, ",
        "#{detail.wareHouseDetailEn,jdbcType=LONGVARCHAR})</foreach></script>",
    })
    int batchInsert(java.util.List<TbWareHouse> list);
}