package com.webank.webase.node.mgr.deploy.entity;

import java.util.Date;

import com.webank.webase.node.mgr.base.enums.ChainStatusEnum;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@EqualsAndHashCode
@ToString
@NoArgsConstructor
public class TbChain {

    public static TbChain build(String chainName,
                                String chainDesc,
                                String version,
                                byte encryptType,
                                ChainStatusEnum status
    ){
        Date now = new Date();
        TbChain chain  = new TbChain();
        chain.setChainName(chainName);
        chain.setDesc(chainDesc);
        chain.setVersion(version);
        chain.setEncryptType(encryptType);
        chain.setStatus(status.getId());
        chain.setCreateTime(now);
        chain.setModifyTime(now);
        return chain;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_chain.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_chain.chain_name
     *
     * @mbg.generated
     */
    private String chainName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_chain.desc
     *
     * @mbg.generated
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_chain.version
     *
     * @mbg.generated
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_chain.encrypt_type
     *
     * @mbg.generated
     */
    private Byte encryptType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_chain.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_chain.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_chain.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;
}