package com.webank.webase.node.mgr.contract.warehouse.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@EqualsAndHashCode
public class TbContractItem implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_contract_item.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_contract_item.contract_name
     *
     * @mbg.generated
     */
    private String contractName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_contract_item.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_contract_item.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_contract_item.ware_house_id
     *
     * @mbg.generated
     */
    private Integer wareHouseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_contract_item.contract_folder_id
     *
     * @mbg.generated
     */
    private Integer contractFolderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_contract_item.contract_source
     *
     * @mbg.generated
     */
    private String contractSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_contract_item.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_contract_item.description_en
     *
     * @mbg.generated
     */
    private String descriptionEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_contract_item
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}