package com.webank.webase.node.mgr.contract.warehouse.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@EqualsAndHashCode
public class TbWareHouse implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ware_house.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ware_house.ware_house_name
     *
     * @mbg.generated
     */
    private String wareHouseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ware_house.ware_house_name_en
     *
     * @mbg.generated
     */
    private String wareHouseNameEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ware_house.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ware_house.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ware_house.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ware_house.ware_house_icon
     *
     * @mbg.generated
     */
    private String wareHouseIcon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ware_house.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ware_house.description_en
     *
     * @mbg.generated
     */
    private String descriptionEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ware_house.ware_house_detail
     *
     * @mbg.generated
     */
    private String wareHouseDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ware_house.ware_house_detail_en
     *
     * @mbg.generated
     */
    private String wareHouseDetailEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_ware_house
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}