package com.webank.webase.node.mgr.lite.contract.warehouse.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * @author marsli
 */
@Data
@ToString
@NoArgsConstructor
@EqualsAndHashCode
public class TbWarehouse implements Serializable {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_warehouse.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_warehouse.warehouse_name
     *
     * @mbg.generated
     */
    private String warehouseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_warehouse.warehouse_name_en
     *
     * @mbg.generated
     */
    private String warehouseNameEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_warehouse.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_warehouse.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_warehouse.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_warehouse.warehouse_icon
     *
     * @mbg.generated
     */
    private String warehouseIcon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_warehouse.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_warehouse.description_en
     *
     * @mbg.generated
     */
    private String descriptionEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_warehouse.warehouse_detail
     *
     * @mbg.generated
     */
    private String warehouseDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_warehouse.warehouse_detail_en
     *
     * @mbg.generated
     */
    private String warehouseDetailEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_warehouse
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}
