package com.webank.webase.node.mgr.lite.contract.warehouse.mapper;

import com.webank.webase.node.mgr.lite.contract.warehouse.entity.TbWarehouse;
import org.apache.ibatis.jdbc.SQL;

public class TbWarehouseSqlProvider {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_warehouse
     *
     * @mbg.generated
     */
    public static final String ALL_COLUMN_FIELDS = "id,warehouse_name,warehouse_name_en,type,create_time,modify_time,warehouse_icon,description,description_en,warehouse_detail,warehouse_detail_en";

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_warehouse
     *
     * @mbg.generated
     */
    public String insertSelective(TbWarehouse record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("tb_warehouse");
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        if (record.getWarehouseName() != null) {
            sql.VALUES("warehouse_name", "#{warehouseName,jdbcType=VARCHAR}");
        }
        if (record.getWarehouseNameEn() != null) {
            sql.VALUES("warehouse_name_en", "#{warehouseNameEn,jdbcType=VARCHAR}");
        }
        if (record.getType() != null) {
            sql.VALUES("type", "#{type,jdbcType=INTEGER}");
        }
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        if (record.getModifyTime() != null) {
            sql.VALUES("modify_time", "#{modifyTime,jdbcType=TIMESTAMP}");
        }
        if (record.getWarehouseIcon() != null) {
            sql.VALUES("warehouse_icon", "#{warehouseIcon,jdbcType=LONGVARCHAR}");
        }
        if (record.getDescription() != null) {
            sql.VALUES("description", "#{description,jdbcType=LONGVARCHAR}");
        }
        if (record.getDescriptionEn() != null) {
            sql.VALUES("description_en", "#{descriptionEn,jdbcType=LONGVARCHAR}");
        }
        if (record.getWarehouseDetail() != null) {
            sql.VALUES("warehouse_detail", "#{warehouseDetail,jdbcType=LONGVARCHAR}");
        }
        if (record.getWarehouseDetailEn() != null) {
            sql.VALUES("warehouse_detail_en", "#{warehouseDetailEn,jdbcType=LONGVARCHAR}");
        }
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_warehouse
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(TbWarehouse record) {
        SQL sql = new SQL();
        sql.UPDATE("tb_warehouse");
        if (record.getWarehouseName() != null) {
            sql.SET("warehouse_name = #{warehouseName,jdbcType=VARCHAR}");
        }
        if (record.getWarehouseNameEn() != null) {
            sql.SET("warehouse_name_en = #{warehouseNameEn,jdbcType=VARCHAR}");
        }
        if (record.getType() != null) {
            sql.SET("type = #{type,jdbcType=INTEGER}");
        }
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        if (record.getModifyTime() != null) {
            sql.SET("modify_time = #{modifyTime,jdbcType=TIMESTAMP}");
        }
        if (record.getWarehouseIcon() != null) {
            sql.SET("warehouse_icon = #{warehouseIcon,jdbcType=LONGVARCHAR}");
        }
        if (record.getDescription() != null) {
            sql.SET("description = #{description,jdbcType=LONGVARCHAR}");
        }
        if (record.getDescriptionEn() != null) {
            sql.SET("description_en = #{descriptionEn,jdbcType=LONGVARCHAR}");
        }
        if (record.getWarehouseDetail() != null) {
            sql.SET("warehouse_detail = #{warehouseDetail,jdbcType=LONGVARCHAR}");
        }
        if (record.getWarehouseDetailEn() != null) {
            sql.SET("warehouse_detail_en = #{warehouseDetailEn,jdbcType=LONGVARCHAR}");
        }
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        return sql.toString();
    }
}
